<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
	<GenerateDocumentationFile>True</GenerateDocumentationFile>
	<IsWindowsOS Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Windows)))' == 'true'">true</IsWindowsOS>
	<OutputType>Library</OutputType>
  </PropertyGroup>
  <PropertyGroup Condition=" $(TargetFramework.EndsWith('windows')) ">
    <UseWPF>True</UseWPF>
    <DefineConstants>$(DefineConstants);UseWPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(IsWindowsOS)'=='true'">
    <DefineConstants>$(DefineConstants);OS_WINDOWS</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;1573;1591</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;1573;1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
  <PackageReference Include="Portable.Xaml" />
  <PackageReference Include="MonoGame.Content.Builder.Task" />
  <PackageReference Include="MonoGame.Extended" />
  <PackageReference Include="MonoGame.Extended.Content.Pipeline" />
  <PackageReference Include="MonoGame.Framework.DesktopGL">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  <PackageReference Include="Prism.Core" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MGUI.MonoGame.Integration\MGUI.MonoGame.Integration.csproj" />
    <ProjectReference Include="..\MGUI.Rendering.Abstractions\MGUI.Rendering.Abstractions.csproj" />
    <ProjectReference Include="..\MGUI.Shared\MGUI.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Page Remove="UI\Themes\BuiltInThemes.xaml" />
    <None Remove="UI\Themes\BuiltInThemes.xaml" />
    <Page Remove="UI\Templates\BuiltInControlTemplates.xaml" />
    <None Remove="UI\Templates\BuiltInControlTemplates.xaml" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="UI\Themes\BuiltInThemes.xaml">
      <Generator>MSBuild:Compile</Generator>
    </EmbeddedResource>
    <EmbeddedResource Include="UI\Templates\BuiltInControlTemplates.xaml">
      <Generator>MSBuild:Compile</Generator>
    </EmbeddedResource>
  </ItemGroup>
</Project>