<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;1573;1591</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;1573;1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MGUI.Rendering.Abstractions\MGUI.Rendering.Abstractions.csproj" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.1.303" />
    <PackageReference Include="MonoGame.Extended" Version="3.8.0" />
    <PackageReference Include="MonoGame.Extended.Content.Pipeline" Version="3.8.0" />
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.1.303">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Prism.Core" Version="8.1.97" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Assets\MonoGameImageResource.cs" />
    <Compile Remove="Helpers\ContentUtils.cs" />
    <Compile Remove="Helpers\RenderUtils.cs" />
    <Compile Remove="Helpers\TextureUtils.cs" />
    <Compile Remove="Input\MonoGameRawInputSource.cs" />
    <Compile Remove="Rendering\BackBufferSurface.cs" />
    <Compile Remove="Rendering\DelegateRenderHost.cs" />
    <Compile Remove="Rendering\DrawTransaction.cs" />
    <Compile Remove="Rendering\MainRenderer.cs" />
    <Compile Remove="Rendering\RenderTargetPool.cs" />
    <Compile Remove="Rendering\View.cs" />
    <Compile Remove="Rendering\Clipping\ClipManager.cs" />
    <Compile Remove="Text\FontManager.cs" />
    <Compile Remove="Text\FontSet.cs" />
    <Compile Remove="Text\SpritefontGenerator.cs" />
    <Compile Remove="Text\Engines\SpriteFontTextEngine.cs" />
  </ItemGroup>
</Project>