<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MGUI.Rendering.Abstractions\MGUI.Rendering.Abstractions.csproj" />
    <ProjectReference Include="..\MGUI.MonoGame.Integration\MGUI.MonoGame.Integration.csproj" />
    <ProjectReference Include="..\MGUI.Shared\MGUI.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
  <PackageReference Include="FontStashSharp.MonoGame" />
  <PackageReference Include="MonoGame.Framework.DesktopGL">
    <PrivateAssets>All</PrivateAssets>
  </PackageReference>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
